### ISSUE TITLE
Let me know

### ISSUE THREAD

**Issue by nickeubank** [nickeubank/ds4humans#2]
If wanna get on zoom some time to talk about notebooks / how this book works.

**Comment by joshclinton** [comment]
That would be good.  Just cloned the repository

**Comment by nickeubank** [comment]
What's your schedule next week and next weekend?

**Comment by joshclinton** [comment]
I am away the 9th-11th in Seattle but otherwise free

**Comment by nickeubank** [comment]
4pm on the 12th?

**Comment by nickeubank** [comment]
Sorry 4pm et. 3pm central.

**Comment by joshclinton** [comment]
Sure

Sent from my iPhone

On Aug 5, 2022, at 8:16 PM, Nick Eubank ***@***.***> wrote:

﻿

Sorry 4pm et. 3pm central.
